/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Category = IDL.Variant({
  'equipment' : IDL.Null,
  'classes' : IDL.Null,
  'atmosphere' : IDL.Null,
  'cleanliness' : IDL.Null,
  'trainers' : IDL.Null,
});
export const Review = IDL.Record({
  'author' : IDL.Text,
  'opinion' : IDL.Text,
  'timestamp' : Time,
  'category' : Category,
  'rating' : IDL.Nat8,
});

export const idlService = IDL.Service({
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'submitReview' : IDL.Func([IDL.Text, IDL.Nat8, Category, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Category = IDL.Variant({
    'equipment' : IDL.Null,
    'classes' : IDL.Null,
    'atmosphere' : IDL.Null,
    'cleanliness' : IDL.Null,
    'trainers' : IDL.Null,
  });
  const Review = IDL.Record({
    'author' : IDL.Text,
    'opinion' : IDL.Text,
    'timestamp' : Time,
    'category' : Category,
    'rating' : IDL.Nat8,
  });
  
  return IDL.Service({
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'submitReview' : IDL.Func([IDL.Text, IDL.Nat8, Category, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };